version: '3.8'

services: 
  postgres:
    image: postgres:15.4-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: waste3d
      POSTGRES_PASSWORD: waste3d
      POSTGRES_DB: beacon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



    mongo:
      image: mongo:latest
      container_name: mongo_db
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db

    nats: 
      image: nats:latest
      container_name: nats_server
      ports:
        - "4222:4222" # порт для клиента
        - "8222:8222" # порт для HTTP-мониторинга
    
    redis:
      image: redis:latest
      container_name: redis_cache
      ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data: